<a href="https://colab.research.google.com/github/Yuvaranii/ChiSquared-Numpy/blob/main/Chi_Squared_%26_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Part-2

Aim: Performing the Hypothesis testing using the Chi-squared test.
The table below is a survey response to 4 categorical variables: people in categories from 18–29, 30–44, 45–64 and >65 years, 
and their movie genre inclination, which is “Action/Adventure”, “Romance” and “Biography”. 
Is there any evidence of a relationship between the age group and their movie genre inclination, at 5% significance level?
       Action/Adventure Romance Biography Total 
18-29    141              68      4         213 
30-44    179              159     7         345 
45-64    220              216     4         440 
65&older 86               101     4         191 
Total    626              544     19        1189


In [1]:
from scipy.stats import chi2_contingency
  
# defining the table
Data = [[141, 68, 4], [179, 159, 7], [220,216,4], [86,101,4]]
Calculated_ChiSq, p,  Degrees_of_Freedom, Expected_Values = chi2_contingency(Data)
  
# interpret p-value
Alpha = 0.05
print("p value is " + str(p))
if p >= Alpha:
    print('Independent (H0 Holds True)') #No Co-relation
else:
    print('Dependent (Reject H0)') #Co-relation exists


p value is 0.00044690833914947634
Dependent (Reject H0)


Part-1

Aim: Revisiting the numpy Details: One feature of NumPy that is powerful but tricky is the ability to perform broadcasting, which really just refers to repeatedly performing an operation over one or more dimensions. Tasks:

The most basic kind of broadcast is with a scalar, in which you can perform a binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to perform that operation with the scalar for every element of the array. To try this out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.

Now, create a 10 × 10 matrix A in which A[i][j] = i + j. You’ll be able to do this using the vector you just created, and adding it to a reshaped version of itself.

A very common use of broadcasting is to standardize data, i.e., to make it have zero mean and unit variance. a. First, create a fake “data set” with 50 examples, each with five dimensions. b. import numpy.random as npr data = np.exp ( npr.randn(50, 5) ) c. Don’t worry too much about what this code is doing at this stage of the course, but for completeness: it imports the NumPy random number generation library, then generates a 50 × 5 matrix of standard normal random variates and exponentiates them. The effect of this is to have a pretend data set of 50 independent and identically-distributed vectors from a log-normal distribution.

Now, compute the mean and standard deviation of each column. This should result in two vectors of length 5. You’ll need to think a little bit about how to use the axis argument to mean and std. Store these vectors into variables and print both of them.

Now standardize the data matrix by 1) subtracting the mean off of each column, and 2) dividing each column by its standard deviation. Do this via broadcasting, and store the result in a matrix called normalized. To verify that you successfully did it, compute the mean and standard deviation of the columns of normalized and print them out.

In [4]:
import numpy as np
x=np.arange(1,11)
x1=x+1
print(x1)

[ 2  3  4  5  6  7  8  9 10 11]


In [7]:
m, n = 10,10
A = np.empty(shape=(m, n), dtype=int)
i, j = np.ogrid[:m, :n]
A = i+j
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [8]:
a = np.zeros((2, 512*512), dtype=np.float32)  
a[1, :] = 1.0  
a[0, :] = 0.1  
print(a)

[[0.1 0.1 0.1 ... 0.1 0.1 0.1]
 [1.  1.  1.  ... 1.  1.  1. ]]


In [9]:
import numpy.random as npr
data = np.exp ( npr.randn(50, 5) )
b=np.std(data,axis=1)
print(b)
c=np.mean(data,axis=1)
print("mean = ",c)

[ 0.9999089   0.6817275   0.35433784  0.88653018  0.31105696  2.81802252
  1.15166094  0.36892758  1.17294621  0.59846941  1.06050983  1.23284256
  1.20929305  1.24817352  0.6646941   0.84056976  0.61692465  1.25650507
  2.16176334  1.04920758  0.44756863  0.73812434  0.2337185   0.80097772
  1.31670404  3.96094191  0.38259591  1.57069557  0.72589652  2.25699632
  1.13932485  0.10198998  2.27738482  1.31021295  1.03553822  1.89228378
  0.27797048  1.37608597  1.45522393  1.06898229 12.47941358  2.30990783
  0.16247811  0.40623212  0.05392475  2.22203689  2.30172072  0.54785647
  0.50434801  0.39966046]
mean =  [1.6060245  0.82648512 0.9094969  1.94489367 0.83525027 3.39887839
 1.33910728 1.66264601 1.69735069 1.42905729 1.66398594 1.49643603
 1.71098401 1.13256296 1.10149039 2.08968706 0.9032659  1.74475561
 1.63921835 1.58722966 0.53737798 1.08699254 0.49048265 1.06470355
 1.07168282 2.83855164 1.12340621 1.45243676 1.24077342 2.03191012
 1.50477664 0.36925952 1.74754616 1.66785365 1.